/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8EqieDkj+gO8VPbtNMMyrbPyyJC/tRqNkfL8Zlc34/9SMiVipZ5NNqgff9j6PZNzma1rNpc/H0oVvjJaiuZK9g==
 */

/* eslint-disable */
// tslint:disable

import Commands from './commands'
import Milks from './milks'
import Poppings from './poppings'
import Purees from './purees'
import Teas from './teas'

interface CommandProducts {
  commandId: Commands['id']
  created_at: ((string | Date)) | null
  id: number & {readonly __brand?: 'command_products_id'}
  milkId: Milks['id']
  poppingId: Poppings['id']
  price: number
  pureeId: Purees['id']
  qteSucre: number
  teaId: Teas['id']
  updated_at: ((string | Date)) | null
}
export default CommandProducts;

interface CommandProducts_InsertParameters {
  commandId: Commands['id']
  created_at?: ((string | Date)) | null
  id: number & {readonly __brand?: 'command_products_id'}
  milkId: Milks['id']
  poppingId: Poppings['id']
  price: number
  pureeId: Purees['id']
  qteSucre: number
  teaId: Teas['id']
  updated_at?: ((string | Date)) | null
}
export type {CommandProducts_InsertParameters}
