/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FcKXUUMNa5K9xzZ1IKEnUuC4rsvVKlvMCPBYTc9mdzi+wYnRziQtNIytHU3Z8zfwH6Hi+vlTRViDjfENzJgtfQ==
 */

/* eslint-disable */
// tslint:disable

interface Milks {
  created_at: ((string | Date)) | null
  description: string
  id: number & {readonly __brand?: 'milks_id'}
  name: string
  price: number
  stock: number
  updated_at: ((string | Date)) | null
}
export default Milks;

interface Milks_InsertParameters {
  created_at?: ((string | Date)) | null
  description: string
  id: number & {readonly __brand?: 'milks_id'}
  name: string
  price: number
  stock: number
  updated_at?: ((string | Date)) | null
}
export type {Milks_InsertParameters}
