/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UXV0WehhOd4HxrzNO/jdNGqOWAVqc2JLZ0kJDvqawrDQaw0zmVYRL5vctRK4kyC+ABW393D79pNKAwDlF5XqYg==
 */

/* eslint-disable */
// tslint:disable

interface Phones {
  area_code: string
  created_at: ((string | Date)) | null
  id: number & {readonly __brand?: 'phones_id'}
  number: number
  updated_at: ((string | Date)) | null
}
export default Phones;

interface Phones_InsertParameters {
  area_code: string
  created_at?: ((string | Date)) | null
  id: number & {readonly __brand?: 'phones_id'}
  number: number
  updated_at?: ((string | Date)) | null
}
export type {Phones_InsertParameters}
