/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Tyt3Nkse9Ajli93Elehw8kAXXoQoQ0wTP9SlAF3foxFCu+UhR/PINhKl9HDW+YhDG2FJsetsL9KIM0mXjKZOVw==
 */

/* eslint-disable */
// tslint:disable

interface Stores {
  address: string
  city: string
  created_at: ((string | Date)) | null
  description: string
  id: number & {readonly __brand?: 'stores_id'}
  name: string
  postal_code: number
  updated_at: ((string | Date)) | null
}
export default Stores;

interface Stores_InsertParameters {
  address: string
  city: string
  created_at?: ((string | Date)) | null
  description: string
  id: number & {readonly __brand?: 'stores_id'}
  name: string
  postal_code: number
  updated_at?: ((string | Date)) | null
}
export type {Stores_InsertParameters}
