/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: pj+Ky4dx2tR9hkCy7XaFVy3sw1f8kCVnMy8d3JMb5j5wLlOt8eeNkqqepZAC0fn8yLfMnks6/Pg4rh0fu+xgag==
 */

/* eslint-disable */
// tslint:disable

import Stores from './stores'
import Users from './users'

interface Commands {
  created_at: ((string | Date)) | null
  id: number & {readonly __brand?: 'commands_id'}
  /**
   * @default In Progress
   */
  status: ("In Progress" | "Waiting For Pick-up" | "Picked-up")
  storeId: Stores['id']
  updated_at: ((string | Date)) | null
  userId: Users['id']
  when_collect: (string | Date)
}
export default Commands;

interface Commands_InsertParameters {
  created_at?: ((string | Date)) | null
  id: number & {readonly __brand?: 'commands_id'}
  /**
   * @default In Progress
   */
  status?: ("In Progress" | "Waiting For Pick-up" | "Picked-up")
  storeId: Stores['id']
  updated_at?: ((string | Date)) | null
  userId: Users['id']
  when_collect: (string | Date)
}
export type {Commands_InsertParameters}
