/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ha+TCKqK+BWV/+w/WXG/Ndy3YUIs7zyMJRwQMH+ku1ilKE4BC9WPevx9JbzCVZnIhtLiNfzExeeS37OKxUSMAQ==
 */

/* eslint-disable */
// tslint:disable

interface FailedJobs {
  connection: string
  exception: unknown
  /**
   * @default CURRENT_TIMESTAMP
   */
  failed_at: (string | Date)
  id: (string | number | BigInt) & {readonly __brand?: 'failed_jobs_id'}
  payload: unknown
  queue: string
  uuid: string
}
export default FailedJobs;

interface FailedJobs_InsertParameters {
  connection: string
  exception: unknown
  /**
   * @default CURRENT_TIMESTAMP
   */
  failed_at?: (string | Date)
  id: (string | number | BigInt) & {readonly __brand?: 'failed_jobs_id'}
  payload: unknown
  queue: string
  uuid: string
}
export type {FailedJobs_InsertParameters}
