/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Uvgd00+iB9HpIE6CFWXl1OCbdEYIijjCZaIT0zqtNfkMd0HnpZdNj3ORZoBIhDjUD8sN1u1vGmL+W27UfBIR8Q==
 */

/* eslint-disable */
// tslint:disable

interface PasswordResets {
  created_at: ((string | Date)) | null
  email: string
  token: string
}
export default PasswordResets;

interface PasswordResets_InsertParameters {
  created_at?: ((string | Date)) | null
  email: string
  token: string
}
export type {PasswordResets_InsertParameters}
