/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CmmZGzTCQXSAT8o6TcxI72oTiGxmwzDuuMkfz5+N8geO66StbNyqpX/3iBKYYNslkSXdTwbfpDvV2cohmAdpQg==
 */

/* eslint-disable */
// tslint:disable

interface Purees {
  created_at: ((string | Date)) | null
  description: string
  id: number & {readonly __brand?: 'purees_id'}
  name: string
  price: number
  stock: number
  updated_at: ((string | Date)) | null
}
export default Purees;

interface Purees_InsertParameters {
  created_at?: ((string | Date)) | null
  description: string
  id: number & {readonly __brand?: 'purees_id'}
  name: string
  price: number
  stock: number
  updated_at?: ((string | Date)) | null
}
export type {Purees_InsertParameters}
