/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 4sDkE1N0OwCbIKkuDtaz6N8n5QrS7zx004GP1rtC3beO+W04b9Lu+88WvG8DwGiv+fPO1KCMcooOhwhi+M7qew==
 */

/* eslint-disable */
// tslint:disable

import Users from './users'

interface Comments {
  created_at: ((string | Date)) | null
  id: number & {readonly __brand?: 'comments_id'}
  message: string
  notes: number
  titre: string
  updated_at: ((string | Date)) | null
  userId: Users['id']
}
export default Comments;

interface Comments_InsertParameters {
  created_at?: ((string | Date)) | null
  id: number & {readonly __brand?: 'comments_id'}
  message: string
  notes: number
  titre: string
  updated_at?: ((string | Date)) | null
  userId: Users['id']
}
export type {Comments_InsertParameters}
