/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 3CVnQmn3ZExDMLF5C/nR5ud8FXGEWUj/nEOlom6Kct+0n7xm4WZPceBnydosf1LrkYiEpDLfzuN/J9I/8JTjbg==
 */

/* eslint-disable */
// tslint:disable

interface Room {
  id: number & {readonly __brand?: 'room_id'}
  name: string
}
export default Room;

interface Room_InsertParameters {
  id: number & {readonly __brand?: 'room_id'}
  name: string
}
export type {Room_InsertParameters}
