/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0EnqWtX0osD21n4s02XP27jdHmMfpwowA18tV8rwkPQo92NxJOKtdiYFqVyRDRhrMQbv46z3CyYd0Eg8gWe19w==
 */

/* eslint-disable */
// tslint:disable

interface Accounts {
  CURRENT_CONNECTIONS: (string | number | BigInt)
  HOST: (string) | null
  MAX_SESSION_CONTROLLED_MEMORY: (string | number | BigInt)
  MAX_SESSION_TOTAL_MEMORY: (string | number | BigInt)
  TOTAL_CONNECTIONS: (string | number | BigInt)
  USER: (string) | null
}
export default Accounts;

interface Accounts_InsertParameters {
  CURRENT_CONNECTIONS: (string | number | BigInt)
  HOST?: (string) | null
  MAX_SESSION_CONTROLLED_MEMORY: (string | number | BigInt)
  MAX_SESSION_TOTAL_MEMORY: (string | number | BigInt)
  TOTAL_CONNECTIONS: (string | number | BigInt)
  USER?: (string) | null
}
export type {Accounts_InsertParameters}
